blueprint:
  name: Basic Presence to Occupancy
  description: Combine single source presence to occupancy
  domain: automation
  input:
    occupancy_sensor:
      name: Occupancy Sensor (Trigger)
      description: This sensor detects if somebody is in the room
      selector:
        entity:
          filter:
            - domain: binary_sensor
    main_light:
      name: Light Switch (Trigger)
      description: Turning off this light switch manually, will cause the room to be considered clear
      selector:
        entity:
          filter:
            - domain: light
    off_smoothing_delay: 
      name: Delay
      description: How long to delay sending off
      default: 00:03:30
      selector:
        delay:
    mqtt_path:
      name: MQTT Item
      description: Just the sensor iself (office_occupancy)
      selector:
        text:

triggers:
  - trigger: state
    entity_id: !input main_light
    from: "on"
    to: "off"
    id: LightOffManually
  - trigger: state
    entity_id: !input occupancy_sensor
    from: null
    to: null
actions:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: template
          value_template: "{{trigger.to_state.context.user_id == none}}"
        - condition: template
          value_template: "{{trigger.to_state.context.parent_id == none}}"
        - condition: trigger
          id:
          - LightOffManually
      sequence:
        - action: mqtt.publish
          data:
            qos: "2"
            retain: true
            topic: home/virtual/!input mqtt_path/state
            payload: "false"
    - conditions:
      - condition: state
        entity_id: !input occupancy_sensor
        state: "on"
      sequence:
        - action: mqtt.publish
          data:
            qos: "2"
            retain: true
            topic: home/virtual/!input mqtt_path/state
            payload: "true"
    - conditions:
      - condition: state
        entity_id: !input occupancy_sensor
        state: "off"
      sequence:
        - delay:
            hours: !input off_smoothing_delay.hours
            minutes: !input off_smoothing_delay.minutes
            seconds: !input off_smoothing_delay.seconds
        - action: mqtt.publish
          data:
            qos: "2"
            retain: true
            topic: home/virtual/!input mqtt_path/state
            payload: "false"
mode: restart
