blueprint:
  name: My Test BP
  description: Testing. V2 - DEPRECATED
  domain: script
  source_url: http://192.168.1.36/gitea/Blueprints/src/branch/master/bptest.yaml
  input:
    target_light:
      name: Lights
      description: The lights to keep in sync.
      selector:
        target:
          entity:
            - domain: input_boolean

sequence:
  - action: input_boolean.turn_on
    target: !input target_light
